spring.application.name=apigateway-service
spring.main.web-application-type=reactive
server.port=0

eureka.instance.instance-id=${spring.application.name}:${random.int}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/,http://localhost:8762/eureka/

spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/order/**
spring.cloud.gateway.routes[0].filters[0]=AddRequestHeader=X-Internal-Call,true
spring.cloud.gateway.routes[0].filters[1]=ApiGatewayFilter

spring.cloud.gateway.routes[1].id=payment-service
spring.cloud.gateway.routes[1].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/payment/**
spring.cloud.gateway.routes[1].filters[0]=AddRequestHeader=X-Internal-Call,true
spring.cloud.gateway.routes[1].filters[1]=ApiGatewayFilter

spring.cloud.gateway.routes[2].id=authentication-service
spring.cloud.gateway.routes[2].uri=lb://AUTHENTICATION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[2].filters[0]=AddRequestHeader=X-Internal-Call,true